# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCurrencyConverterApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCurrencyConverterApp
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Alamofire'

  target 'MyCurrencyConverterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCurrencyConverterAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
